version: '3'

services:
  api:
    image: flaviogf/extra_hours:latest
    ports:
      - 80:80
    entrypoint: |
      pipenv run gunicorn server:app --bind 0.0.0.0:80 --worker-class sanic.worker.GunicornWorker
